### ISSUE TITLE
Use git instead of uploading files

### ISSUE THREAD

**Issue by ionut-tanasa** [dasuchin/grunt-ssh-deploy#36]
Hi there,

First of all. Thank you! 

I am using your module with [grunt-build-control](https://github.com/robwierzbowski/grunt-build-control) also.

Wouldn't it be helpful that, instead of uploading the files straight from the local filesystem, the module clones the repository while logged on the server? 

Basically all it's needed in the configuration is the repository url and the branch to pull from. And the command to do that obviously.

What do you think?

**Comment by lochstar** [comment]
I use [grunt-ssh](https://github.com/chuckmo/grunt-ssh) for tasks such as this.

**Comment by dasuchin** [comment]
The reason I wrote this is because there were already tools out there that did that, and I wanted to just push from my local files instead of having to push to the repo first. It could certainly be added in as an option, but as of right now I have no plans for it. 

If someone wants to add this in as an option, I would accept a pull request.
